# Generated by Django 3.2.7 on 2021-10-04 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('create_time', models.IntegerField()),
                ('user', models.ManyToManyField(related_name='group', to='src.User')),
            ],
        ),
    ]
