# Generated by Django 3.2.7 on 2021-10-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_auto_20211004_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('message_type', models.CharField(db_index=True, max_length=10)),
                ('created_time', models.IntegerField(default=0)),
            ],
        ),
    ]
